[build-system]
requires = ["setuptools>=70", "wheel", "setuptools-scm[toml]>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "node-fdm"
version = "0.1.0"
description = "Neural ODE model for aircraft flight dynamics"
readme = "README.md"
requires-python = ">=3.11"
license = { file = "LICENCE.md" }
authors = [{name = "Gabriel JARRY", email = "gabriel.jarry@eurocontrol.int"}, 
           { name = "Xavier OLIVE", email = "xavier.olive@onera.fr" }, 
           { name = "Ramon DALMAU", email = "ramon.dalmau-codina@eurocontrol.int" }, 
           { name = "Philippe VERY", email = "philippe.very@eurocontrol.int" },
           ]


dynamic = ["version"]

dependencies = [
    "torch>=2.0.0",
    "torchdiffeq>=0.2.3",
    "numpy>=1.24",
    "pandas>=2.0",
    "scipy>=1.10",
    "pyarrow>=12.0",
    "joblib>=1.3",

]

[project.optional-dependencies]
all = [
    "traffic>=2.10.2",
    "fastmeteo>=1.1.0",
    "click>=8.1",
    "tqdm>=4.66",
    "matplotlib>=3.7",
    "altair>=5.0",
    "cairosvg>=2.7",
    ]

bada = [
    "pyBADA>=0.1.7",
    ]
    

test = [
    "pytest>=7.4",
    ]

[project.urls]
Homepage = "https://github.com/eurocontrol"

[tool.setuptools]
package-dir = {"" = "node_fdm"}

[tool.setuptools.packages.find]
where = ["."]
include = [
    "node_fdm*",
    "code*",
    "preprocessing*",
    "pybada_predictor*",
    "utils*",
]
