paths:
  data_dir: "TODO"

  download_dir: "downloaded_parquet"
  preprocess_dir: "preprocessed_parquet"
  process_dir: "processed_flights"
  predicted_dir: "predicted_flights"
  bada_dir: "bada_flights"
  models_dir: "models"
  figure_dir: "figures"

  era5_cache_dir: "era5_cache"

era5_features:
  - u_component_of_wind
  - v_component_of_wind
  - temperature

typecodes:
  - A320
  - A20N
  - A21N
  - A319
  - A321
  - A333
  - A359
  - AT76
  - B38M
  - B738
  - E190

bada:
  bada_4_2_dir: "TODO"
